// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { RouteObject } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ConfigProviderProps } from 'antd';
import { createOpenApiHttp } from 'openapi-msw';
import type { paths } from './apis/api-types';

export * from '@tanstack/react-query';
// export * from './lang.ts';
export * from './hooks';
export * from './apis';
export * from './YDErrorBoundary.tsx';
export * from '@xybot/i18n';

export const microProps: { nbsName: string; baseroute: string } = {
  appName: window.__MICRO_APP_NAME__,
  baseroute: window.__MICRO_APP_BASE_ROUTE__ || '',
  ...window?.microApp?.getData()
};

export const projectProps: { baseroute: string } = {
  // 通过构建process.env注入
  baseroute: window.YD?.__PROJECT_APP_BASE_ROUTE__ || ''
};

export interface IApp {
  antd?: ConfigProviderProps;
  afterRoutes?: (routes: RouteObject[]) => RouteObject[];
  apis?: {
    beforeRequest?: (req: Request) => Promise<Request>;
    afterResponse?: (res: Response) => Promise<Response>;
  };
}
